Genericai stats (#36)
* Atskirtas frontend ir backend i skirtingus projektus

* introduced recentscores and recent mistake counts

* Changed some variable names, added generic class

* \PSInzinerija\Frontend\Games\SimonSays\SimonSaysManager.cs(5,21): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'PSInzinerij
a1' (are you missing an assembly reference?)

* project launches, no generics done yet

* Added a service implementation

Different game stats GetStatsAsync method should work, needs looking into

* Sukurtas controlleris GameStats

* changed the service accordingly, also added stat saving into simonsays, needs changing user id

* changed arrays to a single field variables, RecentScore for every game, MostRecentTime for simon says and single field GameMistakes for visual memory

* added a timer for recent time tracking

* fixed names and types accordingly

* Update GameStatsController.cs

* fixed names

* Fixed namespaces, reworked GameStatsService

* Remade Controller

* changed name of th class

* another name change

* Unhandled exceptions su FetchDataSync metodais both simonsays ir visualmemory

* kazkodel neloadina stats from previous games, gal json serialization issue?

* Issues solved

---------

Co-authored-by: Mykolas Budrys <mykolas.budrys@gmail.com>